name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: ./app
#         push: true
#         tags: ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Deploy to DigitalOcean Droplet
#       env:
#         DO_DROPLET_IP: ${{ secrets.DO_DROPLET_IP }}
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#       run: |
#         ssh -o StrictHostKeyChecking=no -i "${{ env.SSH_PRIVATE_KEY }}" root@${{ env.DO_DROPLET_IP }} << 'EOF'
#         docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest
#         docker stop app || true
#         docker rm app || true
#         docker run -d --name app -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest
#         EOF
